apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  replicas: 3
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: yonesko/microservice-2021-03:kuber_dz_2
        imagePullPolicy: Always
        env:
          - name: PG_URI
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: PG_URI
        ports:
          - name: web
            containerPort: 8080
