apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-initdb-job
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-initdb-job
    spec:
      restartPolicy: Never
      containers:
        - name: initdb
          env:
            - name: PG_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: PG_URI
          image: postgres:latest
          command:
            - sh
            - "-c"
            - |
              psql "$PG_URI" <<EOF
                CREATE TABLE users (
              id serial PRIMARY KEY,
              username VARCHAR ( 50 )  NOT NULL,
              firstName VARCHAR ( 50 ) NOT NULL,
              lastName VARCHAR ( 50 ) NOT NULL,
              email VARCHAR ( 50 )  NOT NULL,
              phone VARCHAR ( 50 )  NOT NULL);
              EOF
  backoffLimit: 2