/*
 * User Service
 *
 * This is simple client API
 *
 * API version: 1.0.0
 * Contact: schetinnikov@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"database/sql"
	"log"
	"net/http"
	"os"

	_ "github.com/lib/pq"

	sw "github.com/yonesko/microservice-2021-03/kuber_dz_2/go-server/go"
)

func main() {
	repo := initRepo()
	log.Printf("Server started")
	log.Fatal(http.ListenAndServe(":8080", sw.NewRouter(repo)))
}

func initRepo() sw.Repo {
	dat, err := sql.Open("postgres", mustEnv("PG_URI"))
	if err != nil {
		log.Fatal(err)
	}
	return sw.PgRepo{Db: dat}
}

func mustEnv(s string) string {
	e := os.Getenv(s)
	if len(e) == 0 {
		panic("no " + s + " in ENV")
	}
	return e
}
